stages:
  - build
  - deploy

before_script:
  - echo Building...
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-image:
  stage: build

  tags:
    - shell

  only:
    - master
  script:
    - docker build
              --cache-from "$CI_REGISTRY_IMAGE:latest"
              --tag "$CI_REGISTRY_IMAGE:latest" .
    
    - docker push "$CI_REGISTRY_IMAGE:latest"
    - 'echo Built image size: $(docker inspect -f "{{ .Size }}" $CI_REGISTRY_IMAGE:latest | numfmt --to=si)'

deploy-app:
  stage: deploy
  only:
    - master
  trigger: kgf/kgf-bot
